### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by emukans** [xingdi-eric-yuan/GATA-public#13]
Going through the readme, I have stuck on `Pre-training Graph Updater by Observation Generation`.
Running `python train_obs_generation.py configs/pretrain_observation_generation.yaml` I'm getting the following error:
```
Traceback (most recent call last):
  File "train_obs_generation.py", line 194, in <module>
    train()
  File "train_obs_generation.py", line 22, in train
    agent = Agent(config)
  File "/GATA-public/agent.py", line 28, in __init__
    self.online_net = KG_Manipulation(config=self.config, word_vocab=self.word_vocab, node_vocab=self.node_vocab, relation_vocab=self.relation_vocab)
  File "/GATA-public/model.py", line 27, in __init__
    self._def_layers()
  File "/GATA-public/model.py", line 88, in _def_layers
    pretrained_embedding_path=self.pretrained_embedding_path)
  File "/GATA-public/layers.py", line 196, in __init__
    self.init_weights()
  File "/GATA-public/layers.py", line 199, in init_weights
    init_embedding_matrix = self.embedding_init()
  File "/GATA-public/layers.py", line 212, in embedding_init
    embedding_initr = H5EmbeddingManager(self.pretrained_embedding_path)
  File "/GATA-public/layers.py", line 144, in __init__
    self.id2word = f['words_flatten'][0].split(r'\n')
TypeError: a bytes-like object is required, not 'str'
```

I have tried both: download `crawl-300d-2M.vec.h5` from `https://bit.ly/2U3Mde2` as written in the readme and download from the source `https://fasttext.cc/docs/en/english-vectors.html` and then process it with this script `https://github.com/xingdi-eric-yuan/imrc_public/blob/master/embedding2h5.py`. The result is the same in both cases.

**Comment by emukans** [comment]
The issue disappeared by downgrading and specifying h5py version: `h5py==2.10.0`

**Comment by xingdi-eric-yuan** [comment]
Thank you @emukans , I have updated this into our requirements.txt accordingly.
