### ISSUE TITLE
pretraining actions

### ISSUE THREAD

**Issue by gari-marcos** [xingdi-eric-yuan/GATA-public#2]
Hello, I am trying to perform the pretraining actions and when I execute the corresponding file for each phase I get the same error: 
```
 python train_command_generation.py config.yaml
Traceback (most recent call last):
  File "train_command_generation.py", line 150, in <module>
    train()
  File "train_command_generation.py", line 19, in train
    env = CommandGenerationData(config)
  File "/home/gari/Documentos/TextWorld/git/GATA-public/command_generation_dataset.py", line 28, in __init__
    self.read_config()
  File "/home/gari/Documentos/TextWorld/git/GATA-public/command_generation_dataset.py", line 71, in read_config
    self.data_path = os.environ['PT_DATA_DIR'] + "/" + self.data_path
  File "/home/gari/anaconda3/envs/gata/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PT_DATA_DIR'
```
Could you tell me which key is missing?
Thank you in advance.

**Comment by xingdi-eric-yuan** [comment]
Hi @gari-marcos , please remove that line (or git pull), that was something I overlooked when cleaning the code. In the other *_dataset.py this also exists. I have pushed a fix. Thanks for reporting it.
