### ISSUE TITLE
Small note: layers.py line 144 and FastTest embeddings download

### ISSUE THREAD

**Issue by MathieuTuli** [xingdi-eric-yuan/GATA-public#20]
When trying to run the first pre-training `Pre-training Graph Updater by Observation Generation`, specifically the
 ```python train_obs_generation.py configs/pretrain_observation_generation.yaml``` 
command, I run into the following error:
```
Traceback (most recent call last):
  File "train_obs_generation.py", line 194, in <module>
    train()
  File "train_obs_generation.py", line 22, in train
    agent = Agent(config)
  File "/home/mat/github/machine-learning/GATA-public/agent.py", line 28, in __init__
    self.online_net = KG_Manipulation(config=self.config, word_vocab=self.word_vocab, node_vocab=self.node_vocab, relation_vocab=self.relation_vocab)
  File "/home/mat/github/machine-learning/GATA-public/model.py", line 27, in __init__
    self._def_layers()
  File "/home/mat/github/machine-learning/GATA-public/model.py", line 81, in _def_layers
    self.word_embedding = Embedding(embedding_size=self.word_embedding_size,
  File "/home/mat/github/machine-learning/GATA-public/layers.py", line 196, in __init__
    self.init_weights()
  File "/home/mat/github/machine-learning/GATA-public/layers.py", line 199, in init_weights
    init_embedding_matrix = self.embedding_init()
  File "/home/mat/github/machine-learning/GATA-public/layers.py", line 212, in embedding_init
    embedding_initr = H5EmbeddingManager(self.pretrained_embedding_path)
  File "/home/mat/github/machine-learning/GATA-public/layers.py", line 144, in __init__
    self.id2word = f['words_flatten'][0].split('\n')
TypeError: a bytes-like object is required, not 'str'

```
I believe line `144` in `layers.py` 
```
self.id2word = f['words_flatten'][0].split('\n')
```
should declare the `\n` string for the split as type `bytes`. i.e. it should be:
```
self.id2word = f['words_flatten'][0].split(b'\n')
```
Doing so solves the issue it seems. Further, I should also note that from the first code block in the README, the command `wget "https://bit.ly/2U3Mde2"` will download the file but with the filename as `2U3Mde2` rather than the required `crawl-300d-2M.vec.h5`, so the README should maybe also be updated accordingly, or equally the command could be changed to `curl -L -o crawl-300d-2M.vec.h5 "https://bit.ly/2U3Mde2"`.

**Comment by xingdi-eric-yuan** [comment]
Thanks for reporting and for the fix. Do you want to make a PR? Otherwise, I can push a commit for it.

**Comment by MathieuTuli** [comment]
I have a branch with the changes, will submit the PR.

**Comment by MathieuTuli** [comment]
PR submitted.
